/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saludcontrol;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jpalazzesi
 */
public class Calculadora extends javax.swing.JFrame {
    String sexo= "hombre";
    Double act;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        // Salvar Recorrido
        Conector co = new Conector();
        co.connect();
        
        co.getUsuarios(cboUsuarios);
        co.getDiario(jtblDiario, cboUsuarios.getSelectedItem().toString());
        new varias().setOcultarColumnasJTable(jtblDiario, new int[]{0,0});
        co.close();
    }
        @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/Weightlift-256.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSexo = new javax.swing.ButtonGroup();
        btActividad = new javax.swing.ButtonGroup();
        popMenu = new javax.swing.JPopupMenu();
        mnuEliminar = new javax.swing.JMenuItem();
        PanelTipodeActividad = new javax.swing.JPanel();
        rdoPoco = new javax.swing.JRadioButton();
        rdoLigero = new javax.swing.JRadioButton();
        rdoModerado = new javax.swing.JRadioButton();
        rdoFuerte = new javax.swing.JRadioButton();
        rdoMuyFuerte = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        PanelMedidas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spEdad = new javax.swing.JSpinner();
        txtPeso = new javax.swing.JTextField();
        rdoHombre = new javax.swing.JRadioButton();
        rdoMujer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtCircunCintura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCircunCuello = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCircunCadera = new javax.swing.JTextField();
        spAltura = new javax.swing.JTextField();
        PanelResultados = new javax.swing.JPanel();
        lblIMC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTMB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblGCStatus = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblMM = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblInfoIMC = new javax.swing.JLabel();
        lblInfoTMB = new javax.swing.JLabel();
        lblInfoGC = new javax.swing.JLabel();
        lblInfoMM = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblICAStatus = new javax.swing.JLabel();
        lblInfoMM1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblIMCStatus = new javax.swing.JLabel();
        lblTMBStatus = new javax.swing.JLabel();
        lblGC1 = new javax.swing.JLabel();
        lblMMStatus = new javax.swing.JLabel();
        lblICA1 = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblDiario = new javax.swing.JTable();
        cboUsuarios = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        mnuEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        mnuEliminar.setText("Eliminar");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        popMenu.add(mnuEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        PanelTipodeActividad.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Actividad"));

        btActividad.add(rdoPoco);
        rdoPoco.setText("Poco / Ningún Ejercicio");
        rdoPoco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoPocoStateChanged(evt);
            }
        });
        rdoPoco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoPocoFocusGained(evt);
            }
        });
        rdoPoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoPocoMouseClicked(evt);
            }
        });
        rdoPoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoPocoActionPerformed(evt);
            }
        });

        btActividad.add(rdoLigero);
        rdoLigero.setText("Ejercicio Ligero");
        rdoLigero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoLigeroFocusGained(evt);
            }
        });

        btActividad.add(rdoModerado);
        rdoModerado.setText("Ejercicio Moderado");
        rdoModerado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoModeradoFocusGained(evt);
            }
        });

        btActividad.add(rdoFuerte);
        rdoFuerte.setText("Ejercicio Fuerte");
        rdoFuerte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoFuerteFocusGained(evt);
            }
        });

        btActividad.add(rdoMuyFuerte);
        rdoMuyFuerte.setText("Ejercicio Muy Fuerte");
        rdoMuyFuerte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdoMuyFuerteFocusGained(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculator.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disk.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTipodeActividadLayout = new javax.swing.GroupLayout(PanelTipodeActividad);
        PanelTipodeActividad.setLayout(PanelTipodeActividadLayout);
        PanelTipodeActividadLayout.setHorizontalGroup(
            PanelTipodeActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipodeActividadLayout.createSequentialGroup()
                .addGroup(PanelTipodeActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTipodeActividadLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(PanelTipodeActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoPoco)
                            .addComponent(rdoLigero)
                            .addComponent(rdoModerado)
                            .addComponent(rdoMuyFuerte)
                            .addComponent(rdoFuerte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelTipodeActividadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTipodeActividadLayout.setVerticalGroup(
            PanelTipodeActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipodeActividadLayout.createSequentialGroup()
                .addGroup(PanelTipodeActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTipodeActividadLayout.createSequentialGroup()
                        .addComponent(rdoPoco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoLigero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoModerado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoFuerte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoMuyFuerte))
                    .addGroup(PanelTipodeActividadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTipodeActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelMedidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas"));

        jLabel1.setText("Edad");

        jLabel2.setText("Peso");

        jLabel3.setText("Altura (en CM)");

        txtPeso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPeso.setText("0");
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesoKeyReleased(evt);
            }
        });

        btSexo.add(rdoHombre);
        rdoHombre.setText("Hombre");
        rdoHombre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoHombreStateChanged(evt);
            }
        });
        rdoHombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rdoHombreFocusLost(evt);
            }
        });
        rdoHombre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rdoHombrePropertyChange(evt);
            }
        });

        btSexo.add(rdoMujer);
        rdoMujer.setText("Mujer");
        rdoMujer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoMujerStateChanged(evt);
            }
        });
        rdoMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMujerActionPerformed(evt);
            }
        });
        rdoMujer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rdoMujerPropertyChange(evt);
            }
        });

        jLabel4.setText("Circunferencia de Cintura (en cm)");

        txtCircunCintura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCircunCintura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCircunCinturaFocusGained(evt);
            }
        });
        txtCircunCintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCircunCinturaKeyReleased(evt);
            }
        });

        jLabel5.setText("Circunferencia de Cuello (en cm)");

        txtCircunCuello.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel16.setText("Circunferencia de Cadera (en cm)");

        txtCircunCadera.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        spAltura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        spAltura.setText("0");
        spAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spAlturaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelMedidasLayout = new javax.swing.GroupLayout(PanelMedidas);
        PanelMedidas.setLayout(PanelMedidasLayout);
        PanelMedidasLayout.setHorizontalGroup(
            PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16)
                    .addGroup(PanelMedidasLayout.createSequentialGroup()
                        .addComponent(rdoHombre)
                        .addGap(18, 18, 18)
                        .addComponent(rdoMujer)))
                .addGap(18, 18, 18)
                .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCircunCuello, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedidasLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(spAltura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCircunCintura, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(txtCircunCadera))
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        PanelMedidasLayout.setVerticalGroup(
            PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMedidasLayout.createSequentialGroup()
                        .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(PanelMedidasLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoMujer)
                            .addComponent(rdoHombre)))
                    .addGroup(PanelMedidasLayout.createSequentialGroup()
                        .addComponent(spEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCircunCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCircunCuello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCircunCadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        lblIMC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblIMC.setText("...");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TMB");

        lblTMB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTMB.setText("...");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("IMC");

        jLabel10.setText("Indice de Masa Corporal");

        jLabel11.setText("Tasa Metabólica Basal");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("GC");

        lblGCStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGCStatus.setText("...");

        jLabel14.setText("Porcentaje de Grasa Corporal");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("MM");

        lblMM.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMM.setText("...");

        jLabel15.setText("Masa Magra");

        lblInfoIMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        lblInfoIMC.setToolTipText("");
        lblInfoIMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoIMCMouseClicked(evt);
            }
        });

        lblInfoTMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        lblInfoTMB.setToolTipText("");
        lblInfoTMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoTMBMouseClicked(evt);
            }
        });

        lblInfoGC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        lblInfoGC.setToolTipText("");
        lblInfoGC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoGCMouseClicked(evt);
            }
        });

        lblInfoMM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        lblInfoMM.setToolTipText("");
        lblInfoMM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoMMMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ICA");

        lblICAStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblICAStatus.setText("...");

        lblInfoMM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info_32.png"))); // NOI18N
        lblInfoMM1.setToolTipText("");
        lblInfoMM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoMM1MouseClicked(evt);
            }
        });

        jLabel18.setText("Indice Cintura Altura");

        lblIMCStatus.setText("...");

        lblTMBStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTMBStatus.setText("...");

        lblGC1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGC1.setText("...");

        lblMMStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMMStatus.setText("...");

        lblICA1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblICA1.setText("...");

        javax.swing.GroupLayout PanelResultadosLayout = new javax.swing.GroupLayout(PanelResultados);
        PanelResultados.setLayout(PanelResultadosLayout);
        PanelResultadosLayout.setHorizontalGroup(
            PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelResultadosLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTMB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelResultadosLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTMBStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelResultadosLayout.createSequentialGroup()
                        .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIMCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoGC)
                    .addComponent(lblInfoIMC)
                    .addComponent(lblInfoTMB))
                .addGap(18, 18, 18)
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addGroup(PanelResultadosLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMMStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblICAStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoMM)
                    .addComponent(lblInfoMM1)))
            .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelResultadosLayout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(lblGC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(740, 740, 740)))
            .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelResultadosLayout.createSequentialGroup()
                    .addGap(624, 624, 624)
                    .addComponent(lblICA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(228, 228, 228)))
        );
        PanelResultadosLayout.setVerticalGroup(
            PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultadosLayout.createSequentialGroup()
                .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelResultadosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblInfoTMB)
                        .addGap(19, 19, 19)
                        .addComponent(lblInfoGC))
                    .addComponent(lblInfoIMC))
                .addGap(7, 7, 7)
                .addComponent(jLabel14))
            .addGroup(PanelResultadosLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblInfoMM1))
            .addComponent(lblInfoMM)
            .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelResultadosLayout.createSequentialGroup()
                    .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMM)
                        .addComponent(jLabel13)
                        .addComponent(lblMMStatus))
                    .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelResultadosLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultadosLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblICAStatus)
                            .addGap(10, 10, 10))))
                .addGroup(PanelResultadosLayout.createSequentialGroup()
                    .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIMC)
                        .addComponent(jLabel9)
                        .addComponent(lblIMCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10)
                    .addGap(7, 7, 7)
                    .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lblTMB)
                        .addComponent(lblTMBStatus))
                    .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelResultadosLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addGap(0, 22, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultadosLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGCStatus)
                            .addContainerGap()))))
            .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultadosLayout.createSequentialGroup()
                    .addContainerGap(120, Short.MAX_VALUE)
                    .addComponent(lblGC1)
                    .addContainerGap()))
            .addGroup(PanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultadosLayout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(lblICA1)
                    .addGap(57, 57, 57)))
        );

        PanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        lblInfo.setToolTipText("");

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setText("Jeremías Palazzesi / http://www.nerdadas.com.ar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguimiento"));

        jtblDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Edad", "Peso", "Altura", "Cintura", "Cuello", "Cadera", "IMC", "TMB", "GC", "MM"
            }
        ));
        jtblDiario.setComponentPopupMenu(popMenu);
        jScrollPane2.setViewportView(jtblDiario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cboUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUsuariosItemStateChanged(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel20.setText("Perfil");

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(736, 736, 736)
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PanelResultados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(18, 18, 18)
                                            .addComponent(cboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnNuevo)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PanelMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PanelTipodeActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelTipodeActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void txtCircunCinturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCircunCinturaKeyReleased

    }//GEN-LAST:event_txtCircunCinturaKeyReleased

    private void txtPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyReleased
    }//GEN-LAST:event_txtPesoKeyReleased

    private void rdoMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMujerActionPerformed

    private void rdoHombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoHombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoHombreFocusLost

    private void rdoHombrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rdoHombrePropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_rdoHombrePropertyChange

    private void rdoMujerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rdoMujerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMujerPropertyChange

    private void rdoHombreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoHombreStateChanged
        // TODO add your handling code here:
        if(rdoHombre.isSelected()){
            sexo = "hombre";
            System.out.println(sexo);
        }else{
            sexo = "mujer";
            System.out.println(sexo);
        }
    }//GEN-LAST:event_rdoHombreStateChanged

    private void rdoMujerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoMujerStateChanged
        // TODO add your handling code here:
         if(rdoHombre.isSelected()){
            sexo = "hombre";
            System.out.println(sexo);
        }else{
            sexo = "mujer";
            System.out.println(sexo);
        }
    }//GEN-LAST:event_rdoMujerStateChanged

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(rdoPoco.isSelected()){
            act = 1.2;
        }
        if(rdoLigero.isSelected()){
            act = 1.375;
        }
        if(rdoModerado.isSelected()){
            act = 1.55;
        }
        if(rdoFuerte.isSelected()){
            act = 1.725;
        }
        if(rdoMuyFuerte.isSelected()){
            act = 1.9;
        }
        lblIMC.setText(new formulas().getIMC(Integer.parseInt(spEdad.getValue().toString()), Double.parseDouble(spAltura.getText()), Double.parseDouble(txtPeso.getText())));
        lblTMB.setText(new formulas().getTMB(Double.parseDouble(txtPeso.getText()), Integer.parseInt(spAltura.getText()), Integer.parseInt(spEdad.getValue().toString()), sexo, act));
        lblGCStatus.setText(new formulas().getGC(sexo, Double.parseDouble(txtCircunCintura.getText()), Double.parseDouble(txtCircunCuello.getText()), Double.parseDouble(spAltura.getText()), Double.parseDouble(txtCircunCadera.getText()), Integer.parseInt(spEdad.getValue().toString())));
        lblICAStatus.setText(new formulas().getIca(Double.parseDouble(spAltura.getText()), Double.parseDouble(txtCircunCintura.getText())));
        lblMM.setText(new formulas().getMM(sexo, Double.parseDouble(txtCircunCintura.getText()), Double.parseDouble(txtCircunCuello.getText()), Double.parseDouble(spAltura.getText()), Double.parseDouble(txtCircunCadera.getText()), Integer.parseInt(spEdad.getValue().toString()), Double.parseDouble(txtPeso.getText())));
        btnSalvar.setEnabled(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rdoPocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoPocoFocusGained
        lblInfo.setText(new formulas().getInfoActividad());
    }//GEN-LAST:event_rdoPocoFocusGained

    private void rdoLigeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoLigeroFocusGained
        // TODO add your handling code here:
        lblInfo.setText(new formulas().getInfoActividad());
    }//GEN-LAST:event_rdoLigeroFocusGained

    private void rdoModeradoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoModeradoFocusGained
        lblInfo.setText(new formulas().getInfoActividad());
    }//GEN-LAST:event_rdoModeradoFocusGained

    private void rdoFuerteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoFuerteFocusGained
        lblInfo.setText(new formulas().getInfoActividad());
    }//GEN-LAST:event_rdoFuerteFocusGained

    private void rdoMuyFuerteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdoMuyFuerteFocusGained
        lblInfo.setText(new formulas().getInfoActividad());
    }//GEN-LAST:event_rdoMuyFuerteFocusGained

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        lblInfo.setText(new formulas().getInfoActividad());
    }//GEN-LAST:event_jLabel8MouseClicked

    private void rdoPocoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoPocoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoPocoStateChanged

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        lblInfo.setText(new formulas().getInfoCintura());
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtCircunCinturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCircunCinturaFocusGained
        lblInfo.setText(new formulas().getInfoCintura());   
    }//GEN-LAST:event_txtCircunCinturaFocusGained

    private void lblInfoIMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoIMCMouseClicked
        lblInfo.setText(new formulas().getInfoIMC());
    }//GEN-LAST:event_lblInfoIMCMouseClicked

    private void lblInfoTMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoTMBMouseClicked
        // TODO add your handling code here:
        lblInfo.setText(new formulas().getInfoTMBData());
    }//GEN-LAST:event_lblInfoTMBMouseClicked

    private void lblInfoGCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoGCMouseClicked
        lblInfo.setText(new formulas().getInfoGC());
    }//GEN-LAST:event_lblInfoGCMouseClicked

    private void lblInfoMMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoMMMouseClicked
        lblInfo.setText(new formulas().getInfoMM());
    }//GEN-LAST:event_lblInfoMMMouseClicked

    private void rdoPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPocoActionPerformed
    }//GEN-LAST:event_rdoPocoActionPerformed

    private void lblInfoMM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoMM1MouseClicked
        lblInfo.setText(new formulas().getInfoCC());
    }//GEN-LAST:event_lblInfoMM1MouseClicked

    private void rdoPocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoPocoMouseClicked
    }//GEN-LAST:event_rdoPocoMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Salvar Recorrido
        Conector co = new Conector();
        co.connect();
        co.setDiario(spEdad.getValue().toString(), txtPeso.getText(), spAltura.getText(), txtCircunCintura.getText()
                , txtCircunCuello.getText(), txtCircunCadera.getText(), lblIMC.getText(), lblTMB.getText(), lblGCStatus.getText(),
                lblMM.getText(), cboUsuarios.getSelectedItem().toString());
        co.getDiario(jtblDiario, cboUsuarios.getSelectedItem().toString());
        new varias().setOcultarColumnasJTable(jtblDiario, new int[]{0,0});
        co.close();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void spAlturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spAlturaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_spAlturaKeyReleased

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        int fila1;
        Object id;
        int resp;
        DefaultTableModel m;
        try{
            fila1 = jtblDiario.getSelectedRow();
            m = (DefaultTableModel) jtblDiario.getModel();
            if(fila1==-1){
                JOptionPane.showMessageDialog(null, "Selecciona un Item");
            }else{
                Conector con = new Conector();
                con.connect();
                con.delDiario(Integer.parseInt(jtblDiario.getModel().getValueAt(fila1, 0).toString()));
                con.getDiario(jtblDiario, cboUsuarios.getSelectedItem().toString());
                con.getUsuarios(cboUsuarios);
                new varias().setOcultarColumnasJTable(jtblDiario, new int[]{0,0});
                con.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Seleccionar!");
        }
    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NuevoUsuario ne = new NuevoUsuario(null, true);
        ne.setLocationRelativeTo(null);
        ne.setTitle("Nuevo Usuario");
        ne.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cboUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUsuariosItemStateChanged
        Conector con = new Conector();
            con.connect();
            con.getDiario(jtblDiario, cboUsuarios.getSelectedItem().toString());
            con.close();
    }//GEN-LAST:event_cboUsuariosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelMedidas;
    private javax.swing.JPanel PanelResultados;
    private javax.swing.JPanel PanelTipodeActividad;
    private javax.swing.ButtonGroup btActividad;
    private javax.swing.ButtonGroup btSexo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalvar;
    public static javax.swing.JComboBox<String> cboUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jtblDiario;
    private javax.swing.JLabel lblGC1;
    private javax.swing.JLabel lblGCStatus;
    private javax.swing.JLabel lblICA1;
    private javax.swing.JLabel lblICAStatus;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblIMCStatus;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfoGC;
    private javax.swing.JLabel lblInfoIMC;
    private javax.swing.JLabel lblInfoMM;
    private javax.swing.JLabel lblInfoMM1;
    private javax.swing.JLabel lblInfoTMB;
    private javax.swing.JLabel lblMM;
    private javax.swing.JLabel lblMMStatus;
    private javax.swing.JLabel lblTMB;
    private javax.swing.JLabel lblTMBStatus;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JRadioButton rdoFuerte;
    private javax.swing.JRadioButton rdoHombre;
    private javax.swing.JRadioButton rdoLigero;
    private javax.swing.JRadioButton rdoModerado;
    private javax.swing.JRadioButton rdoMujer;
    private javax.swing.JRadioButton rdoMuyFuerte;
    private javax.swing.JRadioButton rdoPoco;
    private javax.swing.JTextField spAltura;
    private javax.swing.JSpinner spEdad;
    private javax.swing.JTextField txtCircunCadera;
    private javax.swing.JTextField txtCircunCintura;
    private javax.swing.JTextField txtCircunCuello;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
